name: arouss_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  table_calendar: ^3.0.2 # Use the latest version available on pub.dev
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.3.0
  flutter_localizations: # add or update this dependency
    sdk: flutter
  google_fonts: ^2.1.0 
  image_picker: ^0.8.2+3
  flutter_colorpicker: ^0.5.0
  path: ^1.8.3
  sqflite: ^2.0.0
  http: ^0.13.3

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/home.png
    - assets/categories.png
    - assets/star.png
    - assets/heart.png
    - assets/profile.png
    - assets/home_outlined.png
    - assets/categories_outlined.png
    - assets/star_outlined.png
    - assets/heart_outlined.png
    - assets/profile_outlined.png
    - assets/invitation.png
    - assets/food.png
    - assets/rings.png
    - assets/married.png
    - assets/success.png
    - assets/pfpbride.png
    - assets/pfpbusiness.png
    - assets/inbox.png
    - assets/inbox_outlined.png
    - assets/plus_icon.png
    - assets/add_icon.png
    - assets/add_outlined_icon.png
    - assets/dress.png
    - assets/product_decoration.png
    - assets/pfpbusiness.png
    - assets/profile_background.png
    - assets/Splash2.png
    - assets/bride_icon.png
    - assets/business_icon.png
    - assets/Splash.png
    - assets/logo.png
    

  fonts:
    - family: Changa
      fonts:
        - asset: assets/ChangaFont.ttf
        
