name: our_wedding_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  table_calendar: ^3.0.2 # Use the latest version available on pub.dev
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.3.0
  flutter_localizations: # add or update this dependency
    sdk: flutter
  google_fonts: ^2.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/home.png
    - assets/categories.png
    - assets/star.png
    - assets/heart.png
    - assets/profile.png
    - assets/home_outlined.png
    - assets/categories_outlined.png
    - assets/star_outlined.png
    - assets/heart_outlined.png
    - assets/profile_outlined.png
    - assets/invitation.png
    - assets/food.png
    - assets/rings.png
    - assets/married.png
  fonts:
    - family: Changa
      fonts:
        - asset: assets/ChangaFont.ttf
        